'use client'

import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from '@/components/ui/accordion'

const faqs = [
  {
    question: 'Is NyayAI a replacement for a lawyer?',
    answer: 'No, NyayAI is not a replacement for professional legal advice. It provides general legal information and guidance to help you understand your rights and options. For complex legal matters, court proceedings, or situations requiring legal representation, you should consult a qualified advocate.',
  },
  {
    question: 'What kind of legal issues can NyayAI help with?',
    answer: 'NyayAI can help with everyday legal issues such as tenant-landlord disputes, employment matters (salary, PF, wrongful termination), consumer complaints, traffic violations, family property matters, banking issues, and understanding basic legal procedures in India.',
  },
  {
    question: 'Is my information kept confidential?',
    answer: 'Yes, we take privacy seriously. Your queries are processed to provide you guidance but are not stored permanently or shared with third parties. However, for sensitive legal matters, we recommend consulting with a lawyer who is bound by attorney-client privilege.',
  },
  {
    question: 'Are the complaint letters legally valid?',
    answer: 'The complaint letters generated by NyayAI follow standard formats used in India and can be submitted to relevant authorities. However, for legal notices or court filings, we recommend having them reviewed by a legal professional to ensure they meet specific requirements.',
  },
  {
    question: 'Is NyayAI free to use?',
    answer: 'Yes, NyayAI is completely free. Our mission is to make basic legal knowledge accessible to all Indian citizens, regardless of their financial situation or background.',
  },
  {
    question: 'What languages does NyayAI support?',
    answer: 'Currently, NyayAI works best with English. You can describe your issues in simple English, and we will provide guidance in easy-to-understand language without complex legal jargon.',
  },
  {
    question: 'How accurate is the legal information provided?',
    answer: 'NyayAI is trained on Indian laws and regulations and strives to provide accurate information. However, laws can change and interpretations may vary. Always verify important information with official sources or legal professionals, especially for critical decisions.',
  },
  {
    question: 'Can NyayAI help me file a case in court?',
    answer: 'NyayAI can explain the general process and requirements for filing cases, but actual court filings require proper legal procedures and often need to be done through a registered advocate. We can help you understand your options and prepare for consultations with lawyers.',
  },
]

export function FaqSection() {
  return (
    <section id="faq" className="border-t border-border bg-muted/30 py-16 sm:py-24">
      <div className="container mx-auto max-w-3xl px-4">
        <div className="mb-12 text-center">
          <h2 className="mb-4 text-3xl font-bold tracking-tight text-foreground sm:text-4xl">
            Frequently Asked Questions
          </h2>
          <p className="text-lg text-muted-foreground">
            Find answers to common questions about NyayAI
          </p>
        </div>

        <Accordion type="single" collapsible className="w-full">
          {faqs.map((faq, index) => (
            <AccordionItem key={index} value={`item-${index}`} className="border-border">
              <AccordionTrigger className="text-left text-base font-medium hover:no-underline">
                {faq.question}
              </AccordionTrigger>
              <AccordionContent className="text-muted-foreground leading-relaxed">
                {faq.answer}
              </AccordionContent>
            </AccordionItem>
          ))}
        </Accordion>
      </div>
    </section>
  )
}
